# Automatically check that the new code is black formatted. 
name: Black formatting
on: [pull_request]

jobs:
    check-black-formatting:
        runs-on: ubuntu-latest
        steps:
        
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        
        - name: Check that new files are blackened
          uses: /SebastianGrans/python-black-pull-request-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: print git log
          run: |
            echo "::set-output name=TAG_NAME::$(git --no-pager log -5)')"

            
